import {Injectable} from '@angular/core';
import {Address} from "../../models/address.model";
import {PlantShop} from "../../models/plant-shop.model";
import {Category} from "../../models/category.model";
import {Item} from "../../models/item.model";
import {Order} from "../../models/order.model";

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  banners = [
    {banner: 'assets/imgs/plants/baby-plant-4.jpg'},
    {banner: 'assets/imgs/plants/house-plant-1.jpg'},
    {banner: 'assets/imgs/plants/house-plant-3.jpg'},
  ];
  plantShops: PlantShop[] = [
    {
      uid: '121d3d',
      cover: 'assets/imgs/plant-shops/echo-cover.jpg',
      name: 'eCHo',
      short_name: 'echo',
      categories: ['House plants', 'rarities', 'baby plants'],
      rating: 4.4,
      delivery_time: 20,
      distance: 1.2,
      price: 22,
    },
    {
      uid: '121c3d',
      cover: 'assets/imgs/plant-shops/santa-lucia-cover.jpg',
      name: 'Santa Lucia',
      short_name: 'santa lucia',
      categories: ['House plants', 'Balcony plants', 'Office plants', 'rarities', 'baby plants'],
      rating: 4.3,
      delivery_time: 30,
      distance: 1.5,
      price: 27,
    },
    {
      uid: '121d3e',
      cover: 'assets/imgs/plant-shops/le-tse-fung-cover.jpg',
      name: 'Le Tsé Fung',
      short_name: 'le tsé fung',
      categories: ['Office plants', 'rarities', 'baby plants'],
      rating: 4.8,
      delivery_time: 30,
      distance: 3.9,
      price: 28,
    },
  ];
  categories: Category[] = [
    {
      id: '121d32f3d',
      name: 'Italian',
      uid: '121c3d',
    },
    {
      id: '1232ssda1d3d',
      name: 'Asian',
      uid: '121d3e',
    },
    {
      id: '331321d3d',
      name: 'Swiss',
      uid: '121d3d',
    }
  ];
  plantShops1: PlantShop[] = [
    {
      uid: '121d3d',
      cover: 'assets/imgs/plant-shops/echo-cover.jpg',
      name: 'eCHo',
      short_name: 'echo',
      categories: ['House plants', 'rarities', 'baby plants'],
      address: {
        id: '1dsfsasdd',
        user_id: '1dsfsaassd',
        title: 'Home',
        address: 'Bahnhofstrasse 1',
        city: 'Zurich',
        zip: '8001',
        canton: 'Zurich',
        lat: 47.378177,
        lng: 8.540192,
      },
      rating: 4.4,
      delivery_time: 20,
      price: 22,
    },
    {
      uid: '121c3d',
      cover: 'assets/imgs/plant-shops/santa-lucia-cover.jpg',
      name: 'Santa Lucia',
      short_name: 'santa lucia',
      categories: ['House plants', 'Balcony plants', 'Office plants', 'rarities', 'baby plants'],
      address: {
        id: '1dsfsassdd',
        user_id: '1dsfsaassd',
        title: 'Home',
        address: 'Zwickelgasse 4',
        city: 'Zurich',
        zip: '8002',
        canton: 'Zurich',
        lat: 47.3768866,
        lng: 8.541694,
      },
      rating: 4.3,
      delivery_time: 30,
      price: 27,
    },
    {
      uid: '121d3e',
      cover: 'assets/imgs/plant-shops/le-tse-fung-cover.jpg',
      name: 'Le Tsé Fung',
      short_name: 'le tsé fung',
      categories: ['Office plants', 'rarities', 'baby plants'],
      address: {
        id: '1dsfsasd',
        user_id: '1dsfsaassd',
        title: 'Home',
        address: 'Rue de la Gare',
        city: 'Lausanne',
        zip: '1000',
        canton: 'Vaud',
        lat: 46.5196535,
        lng: 6.6322734,
      },
      rating: 4.8,
      delivery_time: 30,
      price: 28,
    },
  ];
  allItems: Item[] = [
    {
      category_id: '1232ssda1d3d',
      cover: 'assets/imgs/plants/office-plant-2.jpg',
      description: "small office plant with tony round leaves",
      id: "i1sdsad",
      name: "Zamioculcas zamiifolia",
      price: 22.7,
      rating: 4.5,
      status: true,
      uid: "121d3e",
      variation: false,
      withPot: false,
    },
    {
      category_id: '1232ssda1d3d',
      cover: 'assets/imgs/plants/office-plant-3.jpg',
      description: "office plant with long leaves but tiny stems",
      id: "i1sdsa3d",
      name: "Euphorbia lactea",
      price: 27.5,
      rating: 4.2,
      status: true,
      uid: "121d3e",
      variation: false,
      withPot: false,
    },
    {
      category_id: '1232ssda1d3d',
      cover: 'assets/imgs/plants/rarity-4.jpg',
      description: "beautiful rare plant with pink leaves",
      id: "i1sdsa343d",
      name: "Aechmea fasciata",
      price: 16.2,
      rating: 4.7,
      status: true,
      uid: "121d3e",
      variation: false,
      withPot: true,
    },
    {
      category_id: '1232ssda1d3d',
      cover: 'assets/imgs/plants/baby-plant-3.jpg',
      description: "Baby plant with small green leaves",
      id: "i1sdsa2343d",
      name: "Adenium obesum",
      price: 18.1,
      rating: 4.8,
      status: true,
      uid: "121d3e",
      variation: false,
      withPot: true,
    },
    {
      category_id: '121d32f3d',
      cover: 'assets/imgs/plants/house-plant-3.jpg',
      description: "small house plant with lush green leaves",
      id: "i2asdsd1",
      name: "Anthurium andraeanum",
      price: 14.5,
      rating: 4.8,
      status: true,
      uid: "121c3d",
      variation: true,
      withPot: true,
    },
    {
      category_id: '121d32f3d',
      cover: 'assets/imgs/plants/balcony-plant-1.jpg',
      description: "large balcony plant cactus spiky leaves",
      id: "i3223sd1",
      name: "Philodendron bipinnatifidum",
      price: 15,
      rating: 4.2,
      status: true,
      uid: "121c3d",
      variation: true,
      withPot: true,
    },
    {
      category_id: '121d32f3d',
      cover: 'assets/imgs/plants/office-plant-1.jpg',
      description: "large office plant with perforated leaves",
      id: "i3245612sd1",
      name: "Tillandsia xerographica",
      price: 14,
      rating: 3.5,
      status: true,
      uid: "121c3d",
      variation: true,
      withPot: true,
    },
    {
      category_id: '121d32f3d',
      cover: 'assets/imgs/plants/rarity-3.jpg',
      description: "Beautiful rare plant with a big creamy white flower stalk",
      id: "i34521232sd1",
      name: "Strelitzia reginae",
      price: 25,
      rating: 4.5,
      status: true,
      uid: "121c3d",
      variation: true,
      withPot: false,
    },
    {
      category_id: '121d32f3d',
      cover: 'assets/imgs/plants/baby-plant-2.jpg',
      description: "Cute tiny baby plant in various colors",
      id: "i321232sd1",
      name: "Sansevieria trifasciata",
      price: 13,
      rating: 4.7,
      status: true,
      uid: "121c3d",
      variation: true,
      withPot: true,
    },
    {
      category_id: '331321d3d',
      cover: 'assets/imgs/plants/house-plant-1.jpg',
      description: "This plant needs a lot of light and water",
      id: "5i3322512sd1",
      name: "Dracaena fragrans",
      price: 16,
      rating: 4.8,
      status: true,
      uid: "121d3d",
      variation: true,
      withPot: true,
    },
    {
      category_id: '331321d3d',
      cover: 'assets/imgs/plants/house-plant-2.jpg',
      description: "This plant is a great choice for beginners, as it is easy to care for",
      id: "5i32212sd1",
      name: "Monstera deliciosa",
      price: 22,
      rating: 4.3,
      status: true,
      uid: "121d3d",
      variation: true,
      withPot: false,
    },
    {
      category_id: '331321d3d',
      cover: 'assets/imgs/plants/rarity-1.jpg',
      description: "this plant with its red leaves is a rarity and only blooms in warm april days",
      id: "5i327123sd1",
      name: "Calathea ornata",
      price: 38,
      rating: 4.1,
      status: true,
      uid: "121d3d",
      variation: true,
      withPot: true,
    },
    {
      category_id: '331321d3d',
      cover: 'assets/imgs/plants/rarity-2.jpg',
      description: "This plant with its yellow leaves has a unique aphrodisiac smell",
      id: "5i3221122sd1",
      name: "Tomato Cake",
      price: 36,
      rating: 4.4,
      status: true,
      uid: "121d3d",
      variation: true,
      withPot: true,
    },
    {
      category_id: '331321d3d',
      cover: 'assets/imgs/plants/baby-plant-1.jpg',
      description: "The spiky leaves are a good treat for sun burn",
      id: "5i321122sd1",
      name: "Alocasia macrorrhizos",
      price: 45,
      rating: 4.7,
      status: true,
      uid: "121d3d",
      variation: true,
      withPot: false,
    },
  ];
  addresses: Address[] = [
    {
      id: '1dsfsasd',
      user_id: '1dsfsaassd',
      title: 'Home',
      address: 'Rue de la Gare',
      city: 'Lausanne',
      zip: '1000',
      canton: 'Vaud',
      lat: 46.5196535,
      lng: 6.6322734,
    },
    {
      id: '1dsfsasdd',
      user_id: '1dsfsaassd',
      title: 'Work',
      address: 'Bahnhofstrasse 1',
      city: 'Zurich',
      zip: '8001',
      canton: 'Zurich',
      lat: 47.378177,
      lng: 8.540192,
    },
    {
      id: '1dsfsassdd',
      user_id: '1dsfsaassd',
      title: 'Home',
      address: 'Zwickelgasse 4',
      city: 'Zurich',
      zip: '8002',
      canton: 'Zurich',
      lat: 47.3768866,
      lng: 8.541694,
    }
  ]
  orders: Order[] = [
    {
      address: {
        title: 'Home',
        id: '1dsfsasd',
        user_id: '1dsfsaassd',
        address: 'Rue de la Gare',
        city: 'Lausanne',
        zip: '1000',
        canton: 'Vaud',
        lat: 46.5196535,
        lng: 6.6322734,
      },
      deliveryCharge: 18,
      grandTotal: 107,
      totalItems: 3,
      id: 'dsfhgf6kjNKN',
      order: [
        {
          category_id: '121d32f3d',
          cover: 'assets/imgs/plants/baby-plant-2.jpg',
          description: "Cute tiny baby plant in various colors",
          id: "i321232sd1",
          name: "Sansevieria trifasciata",
          price: 13,
          rating: 4.7,
          status: true,
          uid: "121c3d",
          variation: true,
          withPot: true,
        },
        {
          category_id: '331321d3d',
          cover: 'assets/imgs/plants/house-plant-1.jpg',
          description: "This plant needs a lot of light and water",
          id: "5i3322512sd1",
          name: "Dracaena fragrans",
          price: 16,
          rating: 4.8,
          status: true,
          uid: "121d3d",
          variation: true,
          withPot: true,
        },
      ],
      paid: 'COD',
      plantShop: {
        uid: '121c3d',
        cover: 'assets/imgs/vegetarian-food.jpg',
        name: 'Santa Lucia',
        short_name: 'santa lucia',
        categories: ['House plants', 'Balcony plants', 'Office plants', 'rarities'],
        address: {
          title: 'Home',
          id: '1dsfsasdd',
          user_id: '1dsfsaassd',
          address: 'Bahnhofstrasse 1',
          city: 'Zurich',
          zip: '8001',
          canton: 'Zurich',
          lat: 47.378177,
          lng: 8.540192,
        },
        rating: 4.3,
        delivery_time: 30,
        price: 27,
      },
      plantShop_id: '121c3d',
      status: 'created',
      time: "Jul. 7, 2022 13:00:23",
      total: 89,
      user_id: '1',
    },
    {
      address:
        {
          title: 'Work',
          id: '1dsfsassdd',
          user_id: '1dsfsaassd',
          address: 'Winkelriedstrasse 15',
          city: 'Zurich',
          zip: '8002',
          canton: 'Zurich',
          lat: 47.38361704352231,
          lng: 8.549818135160576,

        },
      deliveryCharge: 20,
      grandTotal: 109,
      id: 'dsfhgf6kjNKN',
      order: [
        {
          category_id: '121d32f3d',
          cover: 'assets/imgs/plants/rarity-3.jpg',
          description: "Beautiful rare plant with a big creamy white flower stalk",
          id: "i34521232sd1",
          name: "Strelitzia reginae",
          price: 25,
          rating: 4.5,
          status: true,
          uid: "121c3d",
          variation: true,
          withPot: false,
        },
        {
          category_id: '121d32f3d',
          cover: 'assets/imgs/plants/baby-plant-2.jpg',
          description: "Cute tiny baby plant in various colors",
          id: "i321232sd1",
          name: "Sansevieria trifasciata",
          price: 13,
          rating: 4.7,
          status: true,
          uid: "121c3d",
          variation: true,
          withPot: true,
        },
      ],
      paid: 'COD',
      plantShop: {
        uid: '121c3d',
        cover: 'assets/imgs/vegetarian-food.jpg',
        name: 'Santa Lucia',
        short_name: 'santa lucia',
        categories: ['Balcony plants', 'Office plants'],
        address: {
          title: 'Home',
          id: '1dsfsasdd',
          user_id: '1dsfsaassd',
          address: 'Bahnhofstrasse 1',
          city: 'Zurich',
          zip: '8001',
          canton: 'Zurich',
          lat: 47.378177,
          lng: 8.540192,
        },
        rating: 4.3,
        delivery_time: 30,
        price: 27,
      },
      plantShop_id: '121c3d',
      status: 'created',
      time: "Jul. 7, 2022 13:00:23",
      total: 89,
      user_id: '1',
      totalItems: 3,
    }
  ]

  constructor() {
  }
}
